require("config.globals")
require("config.startup")
require("config.general")
require("config.animations")
require("config.input")
require("config.rules")
require("config.bindings")
require("config.monitors")
