require("config.monitors")
require("config.startup")
require("config.general")
require("config.animations")
require("config.input")
require("config.gestures")
require("config.bindings")
require("config.rules")