hide_return_action = true

theme = "rose-pine"

[providers]
default = [
  "desktopapplications",
]
empty = ["desktopapplications"]

[[providers.prefixes]]
prefix = ";"
provider = "providerlist"

[[providers.prefixes]]
prefix = ">"
provider = "runner"

[[providers.prefixes]]
prefix = "*"
provider = "bluetooth"

[[providers.prefixes]]
prefix = "!"
provider = "menus:power"
