# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json
gui:
  returnImmediately: true
customCommands:
  services:
    - name: up watch
      command: '{{ .DockerCompose }} up --watch'
